2025-07-31 14:59:02.400 [main] ERROR c.g.p.sqlitetest.UserRepository - Failed to create users table
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:444)
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:44)
	at com.grapecity.phoenix.sqlitetest.MainProcess.initializeDatabase(MainProcess.java:165)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:115)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
Caused by: java.sql.SQLException: opening db: 'C:\Code\Rubbish\sqlite-test\nfs-test.db?auto_vacuum=INCREMENTAL&wal_checkpoint=TRUNCATE': The filename, directory name, or volume label syntax is incorrect
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:271)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:106)
	at org.sqlite.JDBC.connect(JDBC.java:79)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	... 6 common frames omitted
2025-07-31 14:59:02.400 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Failed to initialize database
com.grapecity.phoenix.sqlitetest.NfsTestException: Failed to create users table
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:51)
	at com.grapecity.phoenix.sqlitetest.MainProcess.initializeDatabase(MainProcess.java:165)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:115)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:444)
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:44)
	... 3 common frames omitted
Caused by: java.sql.SQLException: opening db: 'C:\Code\Rubbish\sqlite-test\nfs-test.db?auto_vacuum=INCREMENTAL&wal_checkpoint=TRUNCATE': The filename, directory name, or volume label syntax is incorrect
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:271)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:106)
	at org.sqlite.JDBC.connect(JDBC.java:79)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	... 6 common frames omitted
2025-07-31 14:59:02.401 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Multi-process test failed
com.grapecity.phoenix.sqlitetest.NfsTestException: Database initialization failed
	at com.grapecity.phoenix.sqlitetest.MainProcess.initializeDatabase(MainProcess.java:175)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:115)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
Caused by: com.grapecity.phoenix.sqlitetest.NfsTestException: Failed to create users table
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:51)
	at com.grapecity.phoenix.sqlitetest.MainProcess.initializeDatabase(MainProcess.java:165)
	... 2 common frames omitted
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:444)
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:44)
	... 3 common frames omitted
Caused by: java.sql.SQLException: opening db: 'C:\Code\Rubbish\sqlite-test\nfs-test.db?auto_vacuum=INCREMENTAL&wal_checkpoint=TRUNCATE': The filename, directory name, or volume label syntax is incorrect
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:271)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:106)
	at org.sqlite.JDBC.connect(JDBC.java:79)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	... 6 common frames omitted
2025-07-31 15:08:00.059 [main] ERROR c.g.p.sqlitetest.UserRepository - Failed to create users table
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:444)
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:44)
	at com.grapecity.phoenix.sqlitetest.MainProcess.initializeDatabase(MainProcess.java:165)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:115)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
Caused by: java.sql.SQLException: opening db: '/C:/Code/Rubbish/sqlite-test/nfs-test.db?auto_vacuum=INCREMENTAL&wal_checkpoint=TRUNCATE': The filename, directory name, or volume label syntax is incorrect
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:271)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:106)
	at org.sqlite.JDBC.connect(JDBC.java:79)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	... 6 common frames omitted
2025-07-31 15:08:00.059 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Failed to initialize database
com.grapecity.phoenix.sqlitetest.NfsTestException: Failed to create users table
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:51)
	at com.grapecity.phoenix.sqlitetest.MainProcess.initializeDatabase(MainProcess.java:165)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:115)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:444)
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:44)
	... 3 common frames omitted
Caused by: java.sql.SQLException: opening db: '/C:/Code/Rubbish/sqlite-test/nfs-test.db?auto_vacuum=INCREMENTAL&wal_checkpoint=TRUNCATE': The filename, directory name, or volume label syntax is incorrect
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:271)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:106)
	at org.sqlite.JDBC.connect(JDBC.java:79)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	... 6 common frames omitted
2025-07-31 15:08:00.060 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Multi-process test failed
com.grapecity.phoenix.sqlitetest.NfsTestException: Database initialization failed
	at com.grapecity.phoenix.sqlitetest.MainProcess.initializeDatabase(MainProcess.java:175)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:115)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
Caused by: com.grapecity.phoenix.sqlitetest.NfsTestException: Failed to create users table
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:51)
	at com.grapecity.phoenix.sqlitetest.MainProcess.initializeDatabase(MainProcess.java:165)
	... 2 common frames omitted
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:444)
	at com.grapecity.phoenix.sqlitetest.UserRepository.createUsersTable(UserRepository.java:44)
	... 3 common frames omitted
Caused by: java.sql.SQLException: opening db: '/C:/Code/Rubbish/sqlite-test/nfs-test.db?auto_vacuum=INCREMENTAL&wal_checkpoint=TRUNCATE': The filename, directory name, or volume label syntax is incorrect
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:271)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
	at org.sqlite.JDBC.createConnection(JDBC.java:106)
	at org.sqlite.JDBC.connect(JDBC.java:79)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	... 6 common frames omitted
2025-07-31 15:09:40.223 [ForkJoinPool.commonPool-worker-2] ERROR c.g.phoenix.sqlitetest.MainProcess - Child process ChildProcess-1 failed with exit code: 1
2025-07-31 15:09:40.223 [ForkJoinPool.commonPool-worker-1] ERROR c.g.phoenix.sqlitetest.MainProcess - Child process ChildProcess-2 failed with exit code: 1
2025-07-31 15:09:43.051 [com.grapecity.phoenix.sqlitetest.MainProcess.main()] ERROR c.g.phoenix.sqlitetest.MainProcess - Process ChildProcess-1 failed with exit code: 1
2025-07-31 15:09:43.051 [com.grapecity.phoenix.sqlitetest.MainProcess.main()] ERROR c.g.phoenix.sqlitetest.MainProcess - Process ChildProcess-2 failed with exit code: 1
2025-07-31 15:09:43.051 [com.grapecity.phoenix.sqlitetest.MainProcess.main()] ERROR c.g.phoenix.sqlitetest.MainProcess - Error monitoring child processes
com.grapecity.phoenix.sqlitetest.NfsTestException: One or more child processes failed
	at com.grapecity.phoenix.sqlitetest.MainProcess.monitorChildProcesses(MainProcess.java:299)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:128)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
	at org.codehaus.mojo.exec.ExecJavaMojo.doMain(ExecJavaMojo.java:371)
	at org.codehaus.mojo.exec.ExecJavaMojo.doExec(ExecJavaMojo.java:360)
	at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0(ExecJavaMojo.java:280)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-07-31 15:09:43.051 [ForkJoinPool.commonPool-worker-1] ERROR c.g.phoenix.sqlitetest.MainProcess - Statistics thread failed
java.lang.IllegalStateException: Could not load JDBC driver class [org.sqlite.JDBC]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.setDriverClassName(DriverManagerDataSource.java:131)
	at com.grapecity.phoenix.sqlitetest.DatabaseConfig.createDataSource(DatabaseConfig.java:21)
	at com.grapecity.phoenix.sqlitetest.DatabaseConfig.createJdbcTemplate(DatabaseConfig.java:42)
	at com.grapecity.phoenix.sqlitetest.MainProcess.lambda$startStatisticsThread$1(MainProcess.java:356)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.ClassNotFoundException: org.sqlite.JDBC
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.setDriverClassName(DriverManagerDataSource.java:128)
	... 10 common frames omitted
2025-07-31 15:09:43.053 [com.grapecity.phoenix.sqlitetest.MainProcess.main()] ERROR c.g.phoenix.sqlitetest.MainProcess - Multi-process test failed
com.grapecity.phoenix.sqlitetest.NfsTestException: One or more child processes failed
	at com.grapecity.phoenix.sqlitetest.MainProcess.monitorChildProcesses(MainProcess.java:299)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:128)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
	at org.codehaus.mojo.exec.ExecJavaMojo.doMain(ExecJavaMojo.java:371)
	at org.codehaus.mojo.exec.ExecJavaMojo.doExec(ExecJavaMojo.java:360)
	at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0(ExecJavaMojo.java:280)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-07-31 15:10:41.118 [ForkJoinPool.commonPool-worker-1] ERROR c.g.phoenix.sqlitetest.MainProcess - Child process ChildProcess-1 failed with exit code: 1
2025-07-31 15:10:41.130 [ForkJoinPool.commonPool-worker-2] ERROR c.g.phoenix.sqlitetest.MainProcess - Child process ChildProcess-2 failed with exit code: 1
2025-07-31 15:10:43.541 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Process ChildProcess-1 failed with exit code: 1
2025-07-31 15:10:43.541 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Process ChildProcess-2 failed with exit code: 1
2025-07-31 15:10:43.542 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Error monitoring child processes
com.grapecity.phoenix.sqlitetest.NfsTestException: One or more child processes failed
	at com.grapecity.phoenix.sqlitetest.MainProcess.monitorChildProcesses(MainProcess.java:299)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:128)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
2025-07-31 15:10:43.551 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Multi-process test failed
com.grapecity.phoenix.sqlitetest.NfsTestException: One or more child processes failed
	at com.grapecity.phoenix.sqlitetest.MainProcess.monitorChildProcesses(MainProcess.java:299)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:128)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
2025-07-31 15:14:26.533 [ForkJoinPool.commonPool-worker-1] ERROR c.g.phoenix.sqlitetest.MainProcess - Child process ChildProcess-1 failed with exit code: 1
2025-07-31 15:14:26.534 [ForkJoinPool.commonPool-worker-2] ERROR c.g.phoenix.sqlitetest.MainProcess - Child process ChildProcess-2 failed with exit code: 1
2025-07-31 15:14:28.939 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Process ChildProcess-1 failed with exit code: 1
2025-07-31 15:14:28.939 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Process ChildProcess-2 failed with exit code: 1
2025-07-31 15:14:28.939 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Error monitoring child processes
com.grapecity.phoenix.sqlitetest.NfsTestException: One or more child processes failed
	at com.grapecity.phoenix.sqlitetest.MainProcess.monitorChildProcesses(MainProcess.java:299)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:128)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
2025-07-31 15:14:28.943 [main] ERROR c.g.phoenix.sqlitetest.MainProcess - Multi-process test failed
com.grapecity.phoenix.sqlitetest.NfsTestException: One or more child processes failed
	at com.grapecity.phoenix.sqlitetest.MainProcess.monitorChildProcesses(MainProcess.java:299)
	at com.grapecity.phoenix.sqlitetest.MainProcess.runTest(MainProcess.java:128)
	at com.grapecity.phoenix.sqlitetest.MainProcess.main(MainProcess.java:77)
